/vis/open OGL
/vis/drawVolume
/vis/viewer/set/autoRefresh true
/vis/scene/add/trajectories smooth

# Fotonları açık mavi (cyan), müonu kırmızı yap
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton cyan
/vis/modeling/trajectories/drawByParticleID-0/set mu- red

# Izgara ve Kamera ayarları
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 72
/vis/viewer/set/viewpointThetaPhi 70 20

# Sadece müon ve optik fotonları gösteren filtre
/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add mu-
/vis/filtering/trajectories/particleFilter-0/add opticalphoton
/run/setCut 10 m
